### ISSUE TITLE
Unecessary/Invalid link in documentation

### ISSUE THREAD

**Issue by TilakMaddy** [codingphasedotcom/rocky#1]
`<a href="#">Sign Up for a Developer Key</a>
`

The following code at the bottom left of the page (https://codingphasedotcom.github.io/rocky-documentation/#) is either invalid or unnecessary , user wastes his time thinking its not working.Please fix it.

Regards,
UI Concerned Guy!

**Comment by codingphasedotcom** [comment]
Thanks will fix it
